### ISSUE TITLE
Geoserver admin UI for isolated workspace configuration?

### ISSUE THREAD

**Issue by ilkkarinne** [geosolutions-it/syke-C121#8]
Not sure if this is already included in the current issues, but just in case:
Need to design and implement/customize Geoserver admin UI views to support isolated workspace configuration options.

**Comment by simboss** [comment]
Dear @ilkkarinne,
this is part of the work we are doing. 

To be more precise, we are updating the workspace model, configuration option in the ui will appear when we created \ update an workspace. 

The idea is to to have something similar to the default workspace component, a checkbox that will allow to specify that a workspace is isolated. This will mark the corresponding workspace and namespace as isolated.

**Comment by ilkkarinne** [comment]
Hi @simboss, sounds good. I'm guessing the in addition to the checkbox, at least the widget for selecting the workspace URL prefix would be needed.

**Comment by simboss** [comment]
Let's hear from @nmco when he gets to this point.

**Comment by nmco** [comment]
When creating or editing an isolated workspace it is possible to provide the desired prefix and select the corresponding URI (this is mandatory information actually) like for a normal workspace:

![image](https://user-images.githubusercontent.com/1590542/32077102-2836eba4-ba9a-11e7-832b-a1da4b10cdbc.png)

In the image above we are creating an isolated workspace that will be listed as an isolated workspace in the global view:

![image](https://user-images.githubusercontent.com/1590542/32077284-c77f3978-ba9a-11e7-89b9-4792cdbbd38b.png)

Isolated workspaces concept implementation was designed \ planned to integrate elegantly with the current GeoServer workspaces concept, this means that in the user point of view the same UI will be used with an extra option. 

Behind the scenes the workspaces handling code was refactored to also handle isolated workspaces, this means no code duplication, easier code to maintain and concise implementation.

**Comment by nmco** [comment]
Can we close this issue @ilkkarinne ?

**Comment by simboss** [comment]
@nmco this should go under the column "In Test" before "Completed".
